/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DeliveryManager;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.DonarStaff.DonarStaffRaisePickUpRequestJPanel;

/**
 *
 * @author jayashree
 */
public class DeliveryManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DeliveryManagerWorkAreaJPanel
     */
    
    JPanel userProcessContainer;
    private Network network;
    private Organization deliveryManagerorganization;
    private Enterprise deliveryEnterprise;
    private UserAccount deliveryManagerUserAccount;
    
    public DeliveryManagerWorkAreaJPanel(JPanel userProcessContainer, Network network, Organization deliveryManagerorganization, Enterprise deliveryEnterprise, UserAccount deliveryManagerUserAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.deliveryManagerorganization = deliveryManagerorganization;
        this.deliveryEnterprise = deliveryEnterprise;
        this.deliveryManagerUserAccount = deliveryManagerUserAccount;
        
        enterpriseName.setText(deliveryEnterprise.getName());
        organizationName.setText(deliveryManagerorganization.getName());
        employeeName.setText(deliveryManagerUserAccount.getEmployee().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPickUpRequests = new javax.swing.JButton();
        enterpriseName = new javax.swing.JLabel();
        enterpriseLabel2 = new javax.swing.JLabel();
        organizationName = new javax.swing.JLabel();
        employeeName = new javax.swing.JLabel();
        enterpriseLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        viewPickUpRequests1 = new javax.swing.JButton();
        viewPickUpRequests2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 228, 140));

        viewPickUpRequests.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        viewPickUpRequests.setIcon(new javax.swing.ImageIcon("/Users/jayashree/Desktop/Aed Images/icons8-pickup-64.png")); // NOI18N
        viewPickUpRequests.setText("View Pick Up Requests");
        viewPickUpRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPickUpRequestsActionPerformed(evt);
            }
        });

        enterpriseName.setText("<value>");

        enterpriseLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel2.setText("Organization:");

        organizationName.setText("<value>");

        employeeName.setText("<value>");

        enterpriseLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel3.setText("Employee:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Delivery Manager Work Area");

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel1.setText("Enterprise:");

        viewPickUpRequests1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        viewPickUpRequests1.setIcon(new javax.swing.ImageIcon("/Users/jayashree/Desktop/Aed Images/icons8-group-task-96.png")); // NOI18N
        viewPickUpRequests1.setText("View Assigned Requests");
        viewPickUpRequests1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPickUpRequests1ActionPerformed(evt);
            }
        });

        viewPickUpRequests2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        viewPickUpRequests2.setIcon(new javax.swing.ImageIcon("/Users/jayashree/Desktop/Aed Images/icons8-bill-64.png")); // NOI18N
        viewPickUpRequests2.setText("Raise Bill");
        viewPickUpRequests2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPickUpRequests2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("/Users/jayashree/Desktop/Aed Images/icons8-low-connection-64 (1).png")); // NOI18N
        jButton1.setText("View Billing Status");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(enterpriseLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enterpriseLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enterpriseLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(organizationName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(employeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewPickUpRequests, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewPickUpRequests1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewPickUpRequests2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(276, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterpriseName))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(organizationName))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeName))
                .addGap(18, 18, 18)
                .addComponent(viewPickUpRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewPickUpRequests1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewPickUpRequests2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewPickUpRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPickUpRequestsActionPerformed
        // TODO add your handling code here:
        DeliveryManagerViewPickUpRequest deliveryManagerViewPickUpRequest = new DeliveryManagerViewPickUpRequest(userProcessContainer, network, deliveryManagerorganization, deliveryEnterprise, deliveryManagerUserAccount);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("DeliveryManagerViewPickUpRequest", deliveryManagerViewPickUpRequest);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewPickUpRequestsActionPerformed

    private void viewPickUpRequests1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPickUpRequests1ActionPerformed
        // TODO add your handling code here:
        
        DeliveryManagerViewRequestsLogJPanel deliveryManagerViewRequestsLogJPanel = new DeliveryManagerViewRequestsLogJPanel(userProcessContainer, network, deliveryManagerorganization, deliveryEnterprise, deliveryManagerUserAccount);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("DeliveryManagerViewPickUpRequest", deliveryManagerViewRequestsLogJPanel);
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_viewPickUpRequests1ActionPerformed

    private void viewPickUpRequests2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPickUpRequests2ActionPerformed
        // TODO add your handling code here:
        DeliveryManagerRaiseInvoiceJPanel deliveryManagerRaiseInvoiceJPanel = new DeliveryManagerRaiseInvoiceJPanel(userProcessContainer, deliveryManagerorganization, network);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("deliveryManagerRaiseInvoiceJPanel", deliveryManagerRaiseInvoiceJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewPickUpRequests2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DeliveryManagerViewBillPaidUnpaidChartJPanel deliveryManagerViewBillPaidUnpaidChartJPanel = new DeliveryManagerViewBillPaidUnpaidChartJPanel (userProcessContainer, deliveryManagerorganization);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("deliveryManagerViewBillPaidUnpaidChartJPanel", deliveryManagerViewBillPaidUnpaidChartJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel employeeName;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel enterpriseLabel2;
    private javax.swing.JLabel enterpriseLabel3;
    private javax.swing.JLabel enterpriseName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel organizationName;
    private javax.swing.JButton viewPickUpRequests;
    private javax.swing.JButton viewPickUpRequests1;
    private javax.swing.JButton viewPickUpRequests2;
    // End of variables declaration//GEN-END:variables
}
