/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NGOManager;

import Business.Enterprise.Enterprise;
import Business.Enterprise.NGOEnterprise;
import Business.Food.FoodItem;
import Business.Food.FoodList;
import Business.Inventory.Packet;
import Business.Organization.Organization;
import Business.WorkQueue.FoodPickUpRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author jayashree
 */
public class ReportsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportsJPanel
     */
    private JPanel userProcessContainer;
    private Organization ngoManagerOrganization;
    private NGOEnterprise ngoEnterprise;

    public ReportsJPanel(JPanel userProcessContainer, Organization ngoManagerOrganization, Enterprise ngoEnterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ngoManagerOrganization = ngoManagerOrganization;
        this.ngoEnterprise = (NGOEnterprise) ngoEnterprise;
        populateStatistics();
        populateWastageGraph();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        totalFoodItems = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        totalPeopleFed = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        totalWasteAvoidedTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        wastageGraph = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 228, 140));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Total Food Items Distributes Till Date:");

        jLabel2.setText("Total people fed till date: ");

        jLabel3.setText("Total waste avaoided (Pounds):");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel5.setText("NGO Manager Work Area - View Reports");

        wastageGraph.setBackground(new java.awt.Color(255, 255, 204));
        wastageGraph.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wastageGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalFoodItems, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalPeopleFed, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalWasteAvoidedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1))
                .addContainerGap(411, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(totalFoodItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(totalPeopleFed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(totalWasteAvoidedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(wastageGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField totalFoodItems;
    private javax.swing.JTextField totalPeopleFed;
    private javax.swing.JTextField totalWasteAvoidedTextField;
    private javax.swing.JPanel wastageGraph;
    // End of variables declaration//GEN-END:variables

    private void populateStatistics() {
        int totalItems = 0;
        int totalNumberOfPeopleFed = 0;
        double totalWasteAvoided = 0.0d;
        for (Packet distributedPacket : ngoEnterprise.getInventory().getDistributedInventory()) {
            FoodItem fi = distributedPacket.getFoodItem();
            totalItems += fi.getQuantity();
            totalNumberOfPeopleFed += distributedPacket.getPeopleFed();
            totalWasteAvoided += fi.getInPounds();
        }
        totalFoodItems.setText(String.valueOf(totalItems));
        totalPeopleFed.setText(String.valueOf(totalNumberOfPeopleFed));
        totalWasteAvoidedTextField.setText(String.valueOf(Math.round(totalWasteAvoided * 100.0) / 100.0));
    }

    private void populateWastageGraph() {

        // Total Wastage
        double totalExpired = 0.0d;
        double totalTestNotPassed = 0.0d;

        for (FoodItem fi : ngoEnterprise.getInventory().getWasteInventory()) {
            if (fi.getTestResult().isTestPassed()) {
                if (fi.getTestResult().getMessage() != null && fi.getTestResult().getMessage().equalsIgnoreCase("EXPIRED")) {
                    totalExpired += fi.getInPounds();
                }
            } else {
                totalTestNotPassed += fi.getInPounds();
            }

        }

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(totalTestNotPassed, "Food Test failed", "Wastage Category");
        dataset.setValue(totalExpired, "Expired Food", "Wastage Category");
        JFreeChart chart = ChartFactory.createBarChart("Wastage Category", "", "Food in Pounds", dataset, PlotOrientation.VERTICAL, true, true, true);
        ChartPanel chartPanel = new ChartPanel(chart);

        wastageGraph.removeAll();
        wastageGraph.add(chartPanel, BorderLayout.CENTER);
        wastageGraph.validate();
    }
}
