/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NGOStaff;

import Business.Enterprise.Enterprise;
import Business.Enterprise.NGOEnterprise;
import Business.Food.FoodItem;
import Business.Inventory.Packet;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jayashree
 */
public class NGOStaffDistributeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NGOStaffDistributeJPanel
     */
    
    private JPanel userProcessContainer;
    private NGOEnterprise ngoEnterprise;
    
    public NGOStaffDistributeJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ngoEnterprise = (NGOEnterprise) enterprise;
        populateStockTable();
        populateDistributedTable();
      
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        edibleInventoryTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        foodQuantity = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        peopleFedInventoryTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        peopleFed = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(255, 228, 140));

        edibleInventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food Item", "Quantity", "Best Before"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(edibleInventoryTable);

        jLabel3.setText("Quantity:");

        peopleFedInventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food Item", "Quantity", "Distributed Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(peopleFedInventoryTable);

        jButton2.setText("Distribute Food");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("People Fed:");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel5.setText("NGO Staff Work Area - Distribute Food");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        jLabel6.setText("Food Items Available in Inventory");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        jLabel7.setText("Food Items Distributed (Distributed Inventory)");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(peopleFed, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(foodQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)
                        .addComponent(jLabel7)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(foodQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel4)
                    .addComponent(peopleFed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) edibleInventoryTable.getModel();
        int selectedRowIndex = edibleInventoryTable.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Please select food items to distribute");
            return;
        }
        
        FoodItem foodItem = (FoodItem) dtm.getValueAt(selectedRowIndex, 0);
        
        int quantity = (Integer) foodQuantity.getValue();
        
        int availableQuantity = foodItem.getQuantity();
        
        Date bestBefore = foodItem.getTestResult().getBestBefore();
        Date today = new Date();
      
         
        if(bestBefore.before(today)){
            
            foodItem.getTestResult().setMessage("Expired");
            
            ngoEnterprise.getInventory().getWasteInventory().add(foodItem);
            ngoEnterprise.getInventory().getEdibleInventory().remove(foodItem);
            JOptionPane.showMessageDialog(null, "Items have expired and have been moved to waste Inventory ");
            populateStockTable();
            return;
        }
        
        
        if(quantity<=0){
            JOptionPane.showMessageDialog(null, "Enter quantity greater than 0");
            return;
        }
        
        if(quantity>availableQuantity){
            JOptionPane.showMessageDialog(null, "Only " + availableQuantity + " items left in stock");
            return;
        }
        
         int peoplefed = (Integer) peopleFed.getValue();
         
        if(peoplefed<=0){
            JOptionPane.showMessageDialog(null, "People fed cannot be negative or 0");
            return;
        }
       
       
        
        FoodItem distributedItem = null;
        
        try {
            distributedItem = (FoodItem) foodItem.clone();
        } catch (CloneNotSupportedException ex) {
            System.out.print("CloneNotSupportedException in NGOStaffDistributeJPanel");
        }
        
         foodItem.setQuantity(availableQuantity-quantity);
         distributedItem.setQuantity(quantity);
         
          Packet packet = new Packet();
          
          packet.setFoodItem(distributedItem);
          packet.setDate(new Date());
          packet.setPeopleFed(peoplefed);
          
        
        if(quantity == availableQuantity){
            ngoEnterprise.getInventory().getEdibleInventory().remove(foodItem);

        }
         
        
         
        ngoEnterprise.getInventory().getDistributedInventory().add(packet);
        populateStockTable();
        populateDistributedTable();
        
        
       // NGOEnterprise e = (NGOEnterprise) enterprise;
        
        //e.getInventory().getDistributedInventory().add();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void populateStockTable(){
        DefaultTableModel dtm = (DefaultTableModel) edibleInventoryTable.getModel();
       dtm.setRowCount(0);

        for(FoodItem fi : ngoEnterprise.getInventory().getEdibleInventory()){
                Object row[] = new Object[3];
                row[0] = fi;
                row[1] = fi.getQuantity();
                row[2] = fi.getTestResult().getBestBefore();
                
                dtm.addRow(row);
        }
        
        
    }
    
    
    public void populateDistributedTable(){
        DefaultTableModel dtm = (DefaultTableModel) peopleFedInventoryTable.getModel();
        dtm.setRowCount(0);

        for(Packet p : ngoEnterprise.getInventory().getDistributedInventory()){
                Object row[] = new Object[3];
                row[0] = p;
                row[1] = p.getFoodItem().getQuantity();
                row[2] = p.getDate();
               
                
                dtm.addRow(row);
        }
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable edibleInventoryTable;
    private javax.swing.JSpinner foodQuantity;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner peopleFed;
    private javax.swing.JTable peopleFedInventoryTable;
    // End of variables declaration//GEN-END:variables
}
